---
- hosts: 
  tasks:
  - name: Install IIS met features en management tools
    ansible.windows.win_feature:
      name: Web-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: ansible.windows.win_feature

  - name: Reboot als dat nodig is 
    ansible.windows.reboot:
    when: ansible.windows.win_feature.reboot_required

