---
- name: ufw
  hosts: 
  become: yes
  
  tasks: 

  - name: Set logging
    community.general.ufw:
      logging: 'on'
      rule: reject
      port: auth
      log: yes

  - name: Allow SSH 
    community.general.ufw:
      rule: allow

  - name: Delete OpenSSH rule
    community.general.ufw:
      rule: allow
      name: OpenSSH
      delete: yes

  - name: Deny all access to port 53
    community.general.ufw:
      rule: deny
      port: '53'

  - name: Allow port range 60000-61000
    community.general.ufw:
      rule: allow
      port: 60000:61000
      proto: tcp

  - name: Allow all access to tcp port 80
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp