---
- hosts: test-ansible
  become: yes
#  become_user: root
#  become_method: sudo

  tasks:    
    
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
  
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
 
  - name: Install Winbind and tools
    become: true
    apt: name={{ item }} state=present
    with_items:
      - samba
      - krb5-user
      - chrony
      - python3-pip
      - winbind
      - libnss-winbind
      - libpam-winbind
