---
- hosts: test-ansible
  become: yes
#  become_user: root
#  become_method: sudo

  tasks:
    - name: Add multiverse repository                                                                                                         
      become: true
      shell: apt-add-repository multiverse -y
      args:
        executable: /bin/bash
        
    - name: Update and upgrade apt packages
      become: true
      apt:
        update: yes
        upgrade: yes
        update_cache: yes
 
 - name: Install Winbind and tools
      become: true
      apt: name={{ item }} state=present
      with_items:
        - samba
        - krb5-user
        - chrony
        - python3-pip
        - winbind
        - libnss-winbind
        - libpam-winbind
