---
- hosts: test-ansible
  become: yes
  
  tasks: 
  - name: Updates && upgrades Linux machine
    shell:
      cmd: apt -y update
      cmd: apt upgrade
      
  - name: Add repository
    shell:
      cmd: tee -a /etc/apt/sources.list <<EOF
      cmd: deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
      cmd: deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe
      cmd: EOF
