---
- name: Configuring some basic router settings through Ansible
  connection: network_cli
  hosts: all
  tasks:

  - name: Changing Device Hostname
    vyos.vyos.vyos_config:
      lines:
      - set system host-name VyOS-testrouter

  - name: login banner want dat is leuk
    vyos.vyos.vyos_banner:
      banner: pre-login
      text: |
        Dit is een moooie banner
      state: present
  
  - name: Gebruiker aanmaken
    vyos.vyos.vyos_user:
      name: routerlogin
      configured_password: P@ssw0rd123!
      update_password: always
      state: present

  - name: stel interface in
    vyos.vyos.vyos_interfaces:
      config:
      - name: eth1
        description: eth1 Configured by Ansible Module
        speed: auto
        duplex: auto
        enabled: yes

  - name: set IP
    vyos.vyos.vyos_l3_interfaces:
      config:
        - name: eth1
          ipv4:
            - address: 10.10.10.1/30

  - name: Remove aangemaakte User
    vyos.vyos.vyos_user:
      name: routerlogin
      state: absent