---
- hosts: all
  tasks:
  - name: Install critical, security en rollups updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      log_path: C:\Temp\ansible-windows-update.txt
      state: installed
      reboot: yes