---
- name: Create Windows Domain Group if it does not exists
  win_domain_group:
    name: "{{ item.group_name }}"
    scope: "{{ item.group_scope }}"
    state: present
  with_items: "{{ user_info }}"

- name: Create Multiple AD Users
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    password_expired: yes
    state: present
    email: '"{{ item.name }}"@example.com'
  with_items: "{{ user_info }}"
