---
- name: invoke SQL powershell
  hosts: all
  tasks:
    - name: Create user
      win_shell: |
        $data = Invoke-Sqlcmd -Query "SELECT * FROM [Board].[dbo].[Mensen] WHERE Creation = 1" -ServerInstance "WIN-SKARNER" -Username "SQL" -Password "Doekoe2020!!"        
        foreach($employee in $data)
        {
        Write-output "Deze statemennt was TRUE en ik ga nu " + $employee.username  + " aanmaken"  
        function Get-RandomCharacters($length, $characters) 
        {
        $random = 1..$length | ForEach-Object { Get-Random -Maximum $characters.length }
        $private:ofs=""
        return [String]$characters[$random]
        }
        function Scramble-String([string]$inputString)
        {     
        $characterArray = $inputString.ToCharArray()   
        $scrambledStringArray = $characterArray | Get-Random -Count $characterArray.Length     
        $outputString = -join $scrambledStringArray
        return $outputString 
        }
 
        $password = Get-RandomCharacters -length 5 -characters 'abcdefghiklmnoprstuvwxyz'
        $password += Get-RandomCharacters -length 1 -characters 'ABCDEFGHKLMNOPRSTUVWXYZ'
        $password += Get-RandomCharacters -length 1 -characters '1234567890'
        $password += Get-RandomCharacters -length 1 -characters '!'
 
        Write-Host $password

        $password = Scramble-String $password
 
        Write-Host $password

        $SecurePassword = $password | ConvertTo-SecureString -AsPlainText -Force

        New-ADUser -Name $employee.username -GivenName $employee.voornaam -Surname $employee.achternaam -SamAccountName $employee.username -Path "OU=Gebruikers,DC=Doekoe,DC=local" -City $employee.stad -AccountPassword $SecurePassword -Enabled $True
        Invoke-Sqlcmd -Query "UPDATE Board.dbo.Mensen SET creation = 0 WHERE ID = $($employee.ID) " -ServerInstance "WIN-SKARNER" -Username "SQL" -Password "Doekoe2020!!"  -OutputSqlErrors $True
        Invoke-Sqlcmd -Query "INSERT INTO Board.dbo.Wachtwoord (ID,wachtwoord) VALUES ($($employee.ID), '$($password)');" -ServerInstance "WIN-SKARNER" -Username "SQL" -Password "Doekoe2020!!"  -OutputSqlErrors $True
        Add-ADGroupMember -Identity $employee.groep -Members $employee.username
        }
    
    - name: Delete Disabled users
      win_shell: |
        Get-ADUser -Filter * -SearchBase "OU=Gebruikers,DC=Doekoe,DC=local"  | Where-Object {$_.Enabled -eq $false} | Remove-Aduser -confirm:$False 
    
    - name: Disable Users 
      win_shell: |
        $data = Invoke-Sqlcmd -Query "SELECT * FROM [Board].[dbo].[Mensen] WHERE State = 0" -ServerInstance "WIN-SKARNER" -Username "SQL" -Password "Doekoe2020!!"        
        foreach($employee in $data)
        {
        Write-output "Deze statemennt was False en ik ga nu " + $employee.username  + " opblazen"
        Disable-ADAccount -Identity $employee.username
        Invoke-Sqlcmd -Query "UPDATE Board.dbo.Mensen SET state = 1 WHERE ID = $($employee.ID) " -ServerInstance "WIN-SKARNER" -Username "SQL" -Password "Doekoe2020!!"  -OutputSqlErrors $True  
        }
    
    