---
- name: AD_Join_Part2_playbook
  hosts: test-ansible
  become: yes

  tasks:
  - name: Set hostname
    shell:
      cmd: apt update
      cmd: hostnamectl set-hostname myubuntu
      
  - name: stop DNS shizzel
    shell:
      cmd: systemctl disable systemd-resolved
      cmd: systemctl stop systemd-resolved
  
  - name: Update en install shit
    shell:
      cmd: apt update
      cmd: apt -y install realmd 
      cmd: apt -y install libnss-sss 
      cmd: apt -y install libpam-sss 
      cmd: apt -y install sssd 
      cmd: apt -y install sssd-tools 
      cmd: apt -y install adcli 
      cmd: apt -y install samba-common-bin 
      cmd: apt -y install oddjob 
      cmd: apt -y install oddjob-mkhomedir 
      cmd: apt -y install packagekit
 
  - name: Enable dns shizzel
    shell: 
      cmd: systemctl enable systemd-resolved
      cmd: systemctl start systemd-resolved
  
  - name: discover babe
    shell: 
      cmd: sudo realm discover doekoe.local
      
  - name: join dinges
    shell: |
      echo "Doekoe2020!" | realm join -U Administrator doekoe.local
      realm permit -g 'linux-admin'

      
      
