---
- name: AD_Join_Part2_playbook
  hosts: test-ansible
  become: yes

  tasks:
  - name: Set hostname
    shell: |
      apt update
      hostnamectl set-hostname myubuntu
      
  - name: stop DNS shizzel
    shell: |
      systemctl disable systemd-resolved
      systemctl stop systemd-resolved
  
  - name: Update en install shit
    shell: |
      apt update
      apt -y install realmd 
      apt -y install libnss-sss 
      apt -y install libpam-sss 
      apt -y install sssd 
      apt -y install sssd-tools 
      apt -y install adcli 
      apt -y install samba-common-bin 
      apt -y install oddjob 
      apt -y install oddjob-mkhomedir 
      apt -y install packagekit
 
  - name: Enable dns shizzel
    shell: |
      systemctl enable systemd-resolved
      systemctl start systemd-resolved
  
  - name: discover babe
    shell: 
      cmd: sudo realm discover doekoe.local
      
  - name: join dinges
    shell: |
      echo "Doekoe2020!" | realm join -U Administrator doekoe.local
      realm permit -g 'linux-admin'

      
      
