---
- name: AD_Join_Part1_playbook
  hosts: test-ansible
  become: yes
  
  tasks: 
  - name: Updates && upgrades Linux machine
    shell: |
      apt -y update
      apt upgrade
      

  - name: APT - Add bionic universe repository
    apt_repository: repo="deb http://us.archive.ubuntu.com/ubuntu/ bionic universe" update_cache=yes
    apt_repository: repo="deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" update_cache=yes
    when: ansible_distribution == "Ubuntu"
    
  - name: reboot
    shell: 
      cmd: reboot
      

    
