---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "P@ssw0rd123!"
mysql_db: "wordpress"
mysql_user: "wordpress-db01"
mysql_password: "password"

#HTTP Settings
http_host: "doekoe.local"
http_conf: "doekoe.local.conf"
http_port: "80"